import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <video width="400" autoPlay loop muted playsInline style={{margin: '0 auto', width: '100%', height: 'auto'}}>
            <source src="sample.mp4" type="video/mp4" />
          </video>
        </div>

      </main>
    </>
  )
}
